version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: disaster-frontend
    ports:
      - "3000:3000"
    networks:
      - disaster-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: disaster-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - disaster-net
    env_file:
      - .env.dev

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always

    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - disaster-net
    env_file:
      - .env.dev
      
volumes:
  postgres-data:


networks:
  disaster-net:
