version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENV: docker    #env 파일 선택 docker,local
    container_name: disaster-frontend
    ports:
      - "3000:3000"
    networks:
      - disaster-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: disaster-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - disaster-net
    env_file:
      - .env.dev

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - disaster-net
    env_file:
      - .env.dev

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - disaster-net
      
volumes:
  postgres-data:


networks:
  disaster-net:
