services:
  proxy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: disaster-backend
    image: ghcr.io/disaster-alert-archive-team/disaster-alert-archive/backend:${API_TAG:-latest}
    #image: ${DOCKER_USER}/disaster-backend:${API_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod


  redis:
    image: redis:7-alpine
    container_name: disaster-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  caddy_data:
  caddy_config:
