version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: disaster-frontend
    ports:
      - "3000:3000"
    networks:
      - disaster-net

  backend:
    build:
      context: ./backend
    container_name: disaster-backend
    ports:
      - "8080:8080"
    networks:
      - disaster-net
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod

networks:
  disaster-net:
