[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = ".next"

[build.ignore]
  command = "git diff --quiet HEAD~ HEAD -- frontend/"

[build.environment]
  npm_config_platform = "linux"
  npm_config_arch = "x64"

[[plugins]]
  package = "@netlify/plugin-nextjs"