spring:
  application:
    name: "backend"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
#    org.springframework.beans.factory: debug
#    org.hibernate.SQL: debug
    com.disaster.alert: debug
    org.springframework.web: debug

server:
  port: 8080

disaster-alert:
  api:
    service-key: ${DISASTER_ALERT_SERVICE_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600 # in seconds
  header: Authorization
  prefix: Bearer


