spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/disaster_archive
    username: postgres
    password: asdf
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600 # in seconds
  refresh-token-expiration: 604800 # in seconds
  header: Authorization
  prefix: Bearer

disaster-alert:
  api:
    service-key: ${DISASTER_ALERT_SERVICE_KEY}