#도커용
spring:
  application:
    name: "backend"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    #    org.springframework.beans.factory: debug
    #    org.hibernate.SQL: debug
    com.disaster.alert: info
    org.springframework.web: debug

server:
  port: 8080

disaster-alert:
  api:
    service-key: ${DISASTER_ALERT_SERVICE_KEY}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 20 # in seconds
  refresh-token-expiration: 604800 # in seconds
  header: Authorization
  prefix: Bearer


