name: backend-deploy

on:
  push:
    branches: [ "develop" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"
      - "deploy/**"
      - "docker-compose.prod.yml"


env:
  IMAGE_NAME: disaster-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}

  remote-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
           script: |
            set -e
            cd ~/apps/disaster
            export DOCKER_USER=${{ secrets.DOCKERHUB_USERNAME }}
            export API_TAG=latest
            echo "🟢 Pulling latest image..."
            DOCKER_USER=$DOCKER_USER API_TAG=$API_TAG docker compose -f docker-compose.prod.yml pull
            echo "🚀 Restarting containers..."
            DOCKER_USER=$DOCKER_USER API_TAG=$API_TAG docker compose -f docker-compose.prod.yml up -d --remove-orphans
            echo "✅ Deployment completed!"
